# Generated by Django 3.2.8 on 2021-10-26 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(default='2000-01-01')),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.IntegerField(choices=[(0, 'Gender'), (1, 'Female'), (2, 'Male')], default=0)),
                ('avatar', models.ImageField(default='Unknown.jpg', upload_to='')),
                ('cover', models.ImageField(default='background.jpg', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
