# Generated by Django 3.2.8 on 2021-11-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
