# Generated by Django 3.2.8 on 2021-11-02 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_auto_20211031_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date sent'),
        ),
    ]
