# Generated by Django 3.2.8 on 2021-11-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_message_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default='', max_length=50),
        ),
    ]
