# Generated by Django 3.2.8 on 2021-11-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0006_room_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cover',
            field=models.ImageField(default='background.png', upload_to=''),
        ),
    ]
